/*
 * RSBC Hub Event API
 * # Summary Event API for the Road Safety BC Hub.  # Version naming convention  X.y - where x = major (breaking) changes, and y = minor (non-breaking) changes.  # Change log  | version | date       | description | | ------- | ---------- | -----------------------------| | 1.1     | 2020-01-30 | JHI-815 Initial event publish API| | 1.2     | 2020-02-19 | JHi-940 Add offender_type_name to EVT_Issuance data model| |         |            | JHi-940 Add non-breaking changes to support event lookup| | 1.3     | 2020-04-21 | JHI-1145 updated API to include additional data elements identified in BI-852 | | 1.4     | 2020-06-19 | JHI-1246 updated API to include payment transaction id | | 1.5     | 2020-08-05 | JHI-1474 Wording Number Field Required for Violation Records | | 1.6     | 2021-06-30 | JHI-1329 Add the ability to record additional ETK processing events | 
 *
 * OpenAPI spec version: 1.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package bcgov.jh.etk.jhetkcommon.model.eventing;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Violation ticket dispute
 */
@ApiModel(description = "Violation ticket dispute")
@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-07-02T15:57:15.869-07:00")
public class VTDispute {
  @JsonProperty("ticket_number")
  private String ticketNumber = null;

  @JsonProperty("count_number")
  private Integer countNumber = null;

  @JsonProperty("dispute_action_date")
  private String disputeActionDate = null;

  /**
   * A - Allegation F - Fine
   */
  public enum DisputeTypeCodeEnum {
    A("A"),
    
    F("F");

    private String value;

    DisputeTypeCodeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DisputeTypeCodeEnum fromValue(String text) {
      for (DisputeTypeCodeEnum b : DisputeTypeCodeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("dispute_type_code")
  private DisputeTypeCodeEnum disputeTypeCode = null;

  @JsonProperty("count_act_regulation")
  private String countActRegulation = null;

  @JsonProperty("compressed_section")
  private String compressedSection = null;

  public VTDispute ticketNumber(String ticketNumber) {
    this.ticketNumber = ticketNumber;
    return this;
  }

   /**
   * Get ticketNumber
   * @return ticketNumber
  **/
  @ApiModelProperty(example = "EZ12345678", value = "")
  public String getTicketNumber() {
    return ticketNumber;
  }

  public void setTicketNumber(String ticketNumber) {
    this.ticketNumber = ticketNumber;
  }

  public VTDispute countNumber(Integer countNumber) {
    this.countNumber = countNumber;
    return this;
  }

   /**
   * Get countNumber
   * minimum: 1
   * @return countNumber
  **/
  @ApiModelProperty(example = "1", value = "")
  public Integer getCountNumber() {
    return countNumber;
  }

  public void setCountNumber(Integer countNumber) {
    this.countNumber = countNumber;
  }

  public VTDispute disputeActionDate(String disputeActionDate) {
    this.disputeActionDate = disputeActionDate;
    return this;
  }

   /**
   * Get disputeActionDate
   * @return disputeActionDate
  **/
  @ApiModelProperty(example = "2019-09-01", value = "")
  public String getDisputeActionDate() {
    return disputeActionDate;
  }

  public void setDisputeActionDate(String disputeActionDate) {
    this.disputeActionDate = disputeActionDate;
  }

  public VTDispute disputeTypeCode(DisputeTypeCodeEnum disputeTypeCode) {
    this.disputeTypeCode = disputeTypeCode;
    return this;
  }

   /**
   * A - Allegation F - Fine
   * @return disputeTypeCode
  **/
  @ApiModelProperty(example = "A", value = "A - Allegation F - Fine")
  public DisputeTypeCodeEnum getDisputeTypeCode() {
    return disputeTypeCode;
  }

  public void setDisputeTypeCode(DisputeTypeCodeEnum disputeTypeCode) {
    this.disputeTypeCode = disputeTypeCode;
  }

  public VTDispute countActRegulation(String countActRegulation) {
    this.countActRegulation = countActRegulation;
    return this;
  }

   /**
   * Get countActRegulation
   * @return countActRegulation
  **/
  @ApiModelProperty(example = "MVA", value = "")
  public String getCountActRegulation() {
    return countActRegulation;
  }

  public void setCountActRegulation(String countActRegulation) {
    this.countActRegulation = countActRegulation;
  }

  public VTDispute compressedSection(String compressedSection) {
    this.compressedSection = compressedSection;
    return this;
  }

   /**
   * Get compressedSection
   * @return compressedSection
  **/
  @ApiModelProperty(example = "146.1", value = "")
  public String getCompressedSection() {
    return compressedSection;
  }

  public void setCompressedSection(String compressedSection) {
    this.compressedSection = compressedSection;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VTDispute vtDispute = (VTDispute) o;
    return Objects.equals(this.ticketNumber, vtDispute.ticketNumber) &&
        Objects.equals(this.countNumber, vtDispute.countNumber) &&
        Objects.equals(this.disputeActionDate, vtDispute.disputeActionDate) &&
        Objects.equals(this.disputeTypeCode, vtDispute.disputeTypeCode) &&
        Objects.equals(this.countActRegulation, vtDispute.countActRegulation) &&
        Objects.equals(this.compressedSection, vtDispute.compressedSection);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ticketNumber, countNumber, disputeActionDate, disputeTypeCode, countActRegulation, compressedSection);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VTDispute {\n");
    
    sb.append("    ticketNumber: ").append(toIndentedString(ticketNumber)).append("\n");
    sb.append("    countNumber: ").append(toIndentedString(countNumber)).append("\n");
    sb.append("    disputeActionDate: ").append(toIndentedString(disputeActionDate)).append("\n");
    sb.append("    disputeTypeCode: ").append(toIndentedString(disputeTypeCode)).append("\n");
    sb.append("    countActRegulation: ").append(toIndentedString(countActRegulation)).append("\n");
    sb.append("    compressedSection: ").append(toIndentedString(compressedSection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

