/*
 * RSBC Hub Event API
 * # Summary Event API for the Road Safety BC Hub.  # Version naming convention  X.y - where x = major (breaking) changes, and y = minor (non-breaking) changes.  # Change log  | version | date       | description | | ------- | ---------- | -----------------------------| | 1.1     | 2020-01-30 | JHI-815 Initial event publish API| | 1.2     | 2020-02-19 | JHi-940 Add offender_type_name to EVT_Issuance data model| |         |            | JHi-940 Add non-breaking changes to support event lookup| | 1.3     | 2020-04-21 | JHI-1145 updated API to include additional data elements identified in BI-852 | | 1.4     | 2020-06-19 | JHI-1246 updated API to include payment transaction id | | 1.5     | 2020-08-05 | JHI-1474 Wording Number Field Required for Violation Records | | 1.6     | 2021-06-30 | JHI-1329 Add the ability to record additional ETK processing events | 
 *
 * OpenAPI spec version: 1.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package bcgov.jh.etk.jhetkcommon.model.eventing;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * Violation ticket payment receipt
 */
@ApiModel(description = "Violation ticket payment receipt")
@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-07-02T15:57:15.869-07:00")
public class VTPayment {
  @JsonProperty("ticket_number")
  private String ticketNumber = null;

  @JsonProperty("count_number")
  private Integer countNumber = null;

  @JsonProperty("transaction_id")
  private String transactionId = null;

  @JsonProperty("payment_card_type")
  private String paymentCardType = null;

  /**
   * S - Intersection safety camera ticket, E - Electronic violation ticket
   */
  public enum PaymentTicketTypeCodeEnum {
    S("S"),
    
    E("E");

    private String value;

    PaymentTicketTypeCodeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PaymentTicketTypeCodeEnum fromValue(String text) {
      for (PaymentTicketTypeCodeEnum b : PaymentTicketTypeCodeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("payment_ticket_type_code")
  private PaymentTicketTypeCodeEnum paymentTicketTypeCode = null;

  @JsonProperty("payment_amount")
  private BigDecimal paymentAmount = null;

  public VTPayment ticketNumber(String ticketNumber) {
    this.ticketNumber = ticketNumber;
    return this;
  }

   /**
   * Get ticketNumber
   * @return ticketNumber
  **/
  @ApiModelProperty(example = "EZ12345678", value = "")
  public String getTicketNumber() {
    return ticketNumber;
  }

  public void setTicketNumber(String ticketNumber) {
    this.ticketNumber = ticketNumber;
  }

  public VTPayment countNumber(Integer countNumber) {
    this.countNumber = countNumber;
    return this;
  }

   /**
   * Get countNumber
   * @return countNumber
  **/
  @ApiModelProperty(example = "1", value = "")
  public Integer getCountNumber() {
    return countNumber;
  }

  public void setCountNumber(Integer countNumber) {
    this.countNumber = countNumber;
  }

  public VTPayment transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Get transactionId
   * @return transactionId
  **/
  @ApiModelProperty(example = "89166", value = "")
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public VTPayment paymentCardType(String paymentCardType) {
    this.paymentCardType = paymentCardType;
    return this;
  }

   /**
   * Get paymentCardType
   * @return paymentCardType
  **/
  @ApiModelProperty(example = "Visa", value = "")
  public String getPaymentCardType() {
    return paymentCardType;
  }

  public void setPaymentCardType(String paymentCardType) {
    this.paymentCardType = paymentCardType;
  }

  public VTPayment paymentTicketTypeCode(PaymentTicketTypeCodeEnum paymentTicketTypeCode) {
    this.paymentTicketTypeCode = paymentTicketTypeCode;
    return this;
  }

   /**
   * S - Intersection safety camera ticket, E - Electronic violation ticket
   * @return paymentTicketTypeCode
  **/
  @ApiModelProperty(value = "S - Intersection safety camera ticket, E - Electronic violation ticket")
  public PaymentTicketTypeCodeEnum getPaymentTicketTypeCode() {
    return paymentTicketTypeCode;
  }

  public void setPaymentTicketTypeCode(PaymentTicketTypeCodeEnum paymentTicketTypeCode) {
    this.paymentTicketTypeCode = paymentTicketTypeCode;
  }

  public VTPayment paymentAmount(BigDecimal paymentAmount) {
    this.paymentAmount = paymentAmount;
    return this;
  }

   /**
   * Get paymentAmount
   * @return paymentAmount
  **/
  @ApiModelProperty(example = "142.0", value = "")
  public BigDecimal getPaymentAmount() {
    return paymentAmount;
  }

  public void setPaymentAmount(BigDecimal paymentAmount) {
    this.paymentAmount = paymentAmount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VTPayment vtPayment = (VTPayment) o;
    return Objects.equals(this.ticketNumber, vtPayment.ticketNumber) &&
        Objects.equals(this.countNumber, vtPayment.countNumber) &&
        Objects.equals(this.transactionId, vtPayment.transactionId) &&
        Objects.equals(this.paymentCardType, vtPayment.paymentCardType) &&
        Objects.equals(this.paymentTicketTypeCode, vtPayment.paymentTicketTypeCode) &&
        Objects.equals(this.paymentAmount, vtPayment.paymentAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ticketNumber, countNumber, transactionId, paymentCardType, paymentTicketTypeCode, paymentAmount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VTPayment {\n");
    
    sb.append("    ticketNumber: ").append(toIndentedString(ticketNumber)).append("\n");
    sb.append("    countNumber: ").append(toIndentedString(countNumber)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    paymentCardType: ").append(toIndentedString(paymentCardType)).append("\n");
    sb.append("    paymentTicketTypeCode: ").append(toIndentedString(paymentTicketTypeCode)).append("\n");
    sb.append("    paymentAmount: ").append(toIndentedString(paymentAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

