//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.02 at 09:47:31 PM PDT 
//


package bcgov.jh.etk.jhetkcommon.model.icbc.evt.mcot;

import java.math.BigDecimal;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CountType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CountType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CountNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://icbc.net/RSI_InformationManager}string_FreeFormText">
 *               &lt;length value="1"/>
 *               &lt;pattern value="[1-3]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Act" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Section" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://icbc.net/RSI_InformationManager}string_FreeFormText">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OffenseDescription" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://icbc.net/RSI_InformationManager}string_FreeFormText">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Amount" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;maxInclusive value="99999.99"/>
 *               &lt;fractionDigits value="2"/>
 *               &lt;totalDigits value="7"/>
 *               &lt;minInclusive value="0.00"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CountType", propOrder = {
    "countNumber",
    "act",
    "section",
    "offenseDescription",
    "amount"
})
public class CountType {

    @XmlElementRef(name = "CountNumber", type = JAXBElement.class, required = false)
    protected JAXBElement<String> countNumber;
    @XmlElementRef(name = "Act", type = JAXBElement.class, required = false)
    protected JAXBElement<String> act;
    @XmlElementRef(name = "Section", type = JAXBElement.class, required = false)
    protected JAXBElement<String> section;
    @XmlElementRef(name = "OffenseDescription", type = JAXBElement.class, required = false)
    protected JAXBElement<String> offenseDescription;
    @XmlElementRef(name = "Amount", type = JAXBElement.class, required = false)
    protected JAXBElement<BigDecimal> amount;

    /**
     * Gets the value of the countNumber property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCountNumber() {
        return countNumber;
    }

    /**
     * Sets the value of the countNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCountNumber(JAXBElement<String> value) {
        this.countNumber = value;
    }

    /**
     * Gets the value of the act property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAct() {
        return act;
    }

    /**
     * Sets the value of the act property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAct(JAXBElement<String> value) {
        this.act = value;
    }

    /**
     * Gets the value of the section property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSection() {
        return section;
    }

    /**
     * Sets the value of the section property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSection(JAXBElement<String> value) {
        this.section = value;
    }

    /**
     * Gets the value of the offenseDescription property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOffenseDescription() {
        return offenseDescription;
    }

    /**
     * Sets the value of the offenseDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOffenseDescription(JAXBElement<String> value) {
        this.offenseDescription = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setAmount(JAXBElement<BigDecimal> value) {
        this.amount = value;
    }

}
