//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.02 at 09:47:31 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://icbc.net/RSI_InformationManager")
package bcgov.jh.etk.jhetkcommon.model.icbc.evt.mcot;
