//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.02 at 09:47:31 PM PDT 
//


package bcgov.jh.etk.jhetkcommon.model.icbc.evt.mcot;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IndividualParty" type="{http://icbc.net/RSI_InformationManager}IndividualPartyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartyType", propOrder = {
    "individualParty"
})
public class PartyType {

    @XmlElement(name = "IndividualParty", required = true)
    protected IndividualPartyType individualParty;

    /**
     * Gets the value of the individualParty property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualPartyType }
     *     
     */
    public IndividualPartyType getIndividualParty() {
        return individualParty;
    }

    /**
     * Sets the value of the individualParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualPartyType }
     *     
     */
    public void setIndividualParty(IndividualPartyType value) {
        this.individualParty = value;
    }

}
