//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.02 at 09:47:31 PM PDT 
//


package bcgov.jh.etk.jhetkcommon.model.icbc.evt.mcot;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VehicleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehicleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RegisteredOwnerName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://icbc.net/RSI_InformationManager}string_FreeFormText">
 *               &lt;maxLength value="83"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TypeCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://icbc.net/RSI_InformationManager}string_FreeFormText">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MakeCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://icbc.net/RSI_InformationManager}string_FreeFormText">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Colour" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://icbc.net/RSI_InformationManager}string_FreeFormText">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Year" type="{http://icbc.net/RSI_InformationManager}string_year" minOccurs="0"/>
 *         &lt;element name="Accident" type="{http://icbc.net/RSI_InformationManager}bool_y_n" minOccurs="0"/>
 *         &lt;element name="VehicleLicense" type="{http://icbc.net/RSI_InformationManager}VehicleLicenseType" minOccurs="0"/>
 *         &lt;element name="NSC" type="{http://icbc.net/RSI_InformationManager}NscType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehicleType", propOrder = {
    "registeredOwnerName",
    "typeCode",
    "makeCode",
    "colour",
    "year",
    "accident",
    "vehicleLicense",
    "nsc"
})
public class VehicleType {

    @XmlElementRef(name = "RegisteredOwnerName", type = JAXBElement.class, required = false)
    protected JAXBElement<String> registeredOwnerName;
    @XmlElementRef(name = "TypeCode", type = JAXBElement.class, required = false)
    protected JAXBElement<String> typeCode;
    @XmlElementRef(name = "MakeCode", type = JAXBElement.class, required = false)
    protected JAXBElement<String> makeCode;
    @XmlElementRef(name = "Colour", type = JAXBElement.class, required = false)
    protected JAXBElement<String> colour;
    @XmlElementRef(name = "Year", type = JAXBElement.class, required = false)
    protected JAXBElement<String> year;
    @XmlElementRef(name = "Accident", type = JAXBElement.class, required = false)
    protected JAXBElement<BoolYN> accident;
    @XmlElementRef(name = "VehicleLicense", type = JAXBElement.class, required = false)
    protected JAXBElement<VehicleLicenseType> vehicleLicense;
    @XmlElementRef(name = "NSC", type = JAXBElement.class, required = false)
    protected JAXBElement<NscType> nsc;

    /**
     * Gets the value of the registeredOwnerName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRegisteredOwnerName() {
        return registeredOwnerName;
    }

    /**
     * Sets the value of the registeredOwnerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRegisteredOwnerName(JAXBElement<String> value) {
        this.registeredOwnerName = value;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTypeCode() {
        return typeCode;
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTypeCode(JAXBElement<String> value) {
        this.typeCode = value;
    }

    /**
     * Gets the value of the makeCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMakeCode() {
        return makeCode;
    }

    /**
     * Sets the value of the makeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMakeCode(JAXBElement<String> value) {
        this.makeCode = value;
    }

    /**
     * Gets the value of the colour property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getColour() {
        return colour;
    }

    /**
     * Sets the value of the colour property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setColour(JAXBElement<String> value) {
        this.colour = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setYear(JAXBElement<String> value) {
        this.year = value;
    }

    /**
     * Gets the value of the accident property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BoolYN }{@code >}
     *     
     */
    public JAXBElement<BoolYN> getAccident() {
        return accident;
    }

    /**
     * Sets the value of the accident property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BoolYN }{@code >}
     *     
     */
    public void setAccident(JAXBElement<BoolYN> value) {
        this.accident = value;
    }

    /**
     * Gets the value of the vehicleLicense property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link VehicleLicenseType }{@code >}
     *     
     */
    public JAXBElement<VehicleLicenseType> getVehicleLicense() {
        return vehicleLicense;
    }

    /**
     * Sets the value of the vehicleLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link VehicleLicenseType }{@code >}
     *     
     */
    public void setVehicleLicense(JAXBElement<VehicleLicenseType> value) {
        this.vehicleLicense = value;
    }

    /**
     * Gets the value of the nsc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link NscType }{@code >}
     *     
     */
    public JAXBElement<NscType> getNSC() {
        return nsc;
    }

    /**
     * Sets the value of the nsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link NscType }{@code >}
     *     
     */
    public void setNSC(JAXBElement<NscType> value) {
        this.nsc = value;
    }

}
