//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.02 at 09:47:31 PM PDT 
//


package bcgov.jh.etk.jhetkcommon.model.icbc.evt.mcot;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ViolationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ViolationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TicketNumber" type="{http://icbc.net/RSI_InformationManager}TicketNumberType"/>
 *         &lt;element name="OffenderDescription">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://icbc.net/RSI_InformationManager}string_required">
 *               &lt;maxLength value="20"/>
 *               &lt;enumeration value="DRIVER"/>
 *               &lt;enumeration value="CYCLIST"/>
 *               &lt;enumeration value="PEDESTRIAN"/>
 *               &lt;enumeration value="PASSENGER"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ViolationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ViolationTime" type="{http://icbc.net/RSI_InformationManager}string_24hr_time"/>
 *         &lt;element name="Highway" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://icbc.net/RSI_InformationManager}string_FreeFormText">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CityCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://icbc.net/RSI_InformationManager}string_FreeFormText">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CityName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://icbc.net/RSI_InformationManager}string_FreeFormText">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DisputeAddress" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://icbc.net/RSI_InformationManager}string_FreeFormText">
 *               &lt;maxLength value="65"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CourtLocation" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://icbc.net/RSI_InformationManager}string_FreeFormText">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Count" type="{http://icbc.net/RSI_InformationManager}CountType" maxOccurs="3"/>
 *         &lt;element name="EVTFormNumber">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://icbc.net/RSI_InformationManager}string_FreeFormText">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ViolationType", propOrder = {
    "ticketNumber",
    "offenderDescription",
    "violationDate",
    "violationTime",
    "highway",
    "cityCode",
    "cityName",
    "disputeAddress",
    "courtLocation",
    "count",
    "evtFormNumber"
})
public class ViolationType {

    @XmlElement(name = "TicketNumber", required = true)
    protected String ticketNumber;
    @XmlElement(name = "OffenderDescription", required = true)
    protected String offenderDescription;
    @XmlElement(name = "ViolationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar violationDate;
    @XmlElement(name = "ViolationTime", required = true)
    protected String violationTime;
    @XmlElementRef(name = "Highway", type = JAXBElement.class, required = false)
    protected JAXBElement<String> highway;
    @XmlElementRef(name = "CityCode", type = JAXBElement.class, required = false)
    protected JAXBElement<String> cityCode;
    @XmlElementRef(name = "CityName", type = JAXBElement.class, required = false)
    protected JAXBElement<String> cityName;
    @XmlElementRef(name = "DisputeAddress", type = JAXBElement.class, required = false)
    protected JAXBElement<String> disputeAddress;
    @XmlElementRef(name = "CourtLocation", type = JAXBElement.class, required = false)
    protected JAXBElement<String> courtLocation;
    @XmlElement(name = "Count", required = true)
    protected List<CountType> count;
    @XmlElement(name = "EVTFormNumber", required = true)
    protected String evtFormNumber;

    /**
     * Gets the value of the ticketNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketNumber() {
        return ticketNumber;
    }

    /**
     * Sets the value of the ticketNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketNumber(String value) {
        this.ticketNumber = value;
    }

    /**
     * Gets the value of the offenderDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffenderDescription() {
        return offenderDescription;
    }

    /**
     * Sets the value of the offenderDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffenderDescription(String value) {
        this.offenderDescription = value;
    }

    /**
     * Gets the value of the violationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getViolationDate() {
        return violationDate;
    }

    /**
     * Sets the value of the violationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setViolationDate(XMLGregorianCalendar value) {
        this.violationDate = value;
    }

    /**
     * Gets the value of the violationTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViolationTime() {
        return violationTime;
    }

    /**
     * Sets the value of the violationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViolationTime(String value) {
        this.violationTime = value;
    }

    /**
     * Gets the value of the highway property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getHighway() {
        return highway;
    }

    /**
     * Sets the value of the highway property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHighway(JAXBElement<String> value) {
        this.highway = value;
    }

    /**
     * Gets the value of the cityCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCityCode() {
        return cityCode;
    }

    /**
     * Sets the value of the cityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCityCode(JAXBElement<String> value) {
        this.cityCode = value;
    }

    /**
     * Gets the value of the cityName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCityName() {
        return cityName;
    }

    /**
     * Sets the value of the cityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCityName(JAXBElement<String> value) {
        this.cityName = value;
    }

    /**
     * Gets the value of the disputeAddress property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDisputeAddress() {
        return disputeAddress;
    }

    /**
     * Sets the value of the disputeAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDisputeAddress(JAXBElement<String> value) {
        this.disputeAddress = value;
    }

    /**
     * Gets the value of the courtLocation property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCourtLocation() {
        return courtLocation;
    }

    /**
     * Sets the value of the courtLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCourtLocation(JAXBElement<String> value) {
        this.courtLocation = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the count property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CountType }
     * 
     * 
     */
    public List<CountType> getCount() {
        if (count == null) {
            count = new ArrayList<CountType>();
        }
        return this.count;
    }

    /**
     * Gets the value of the evtFormNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEVTFormNumber() {
        return evtFormNumber;
    }

    /**
     * Sets the value of the evtFormNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEVTFormNumber(String value) {
        this.evtFormNumber = value;
    }

}
