package bcgov.jh.etk.jhetkcommon.util;

import org.junit.Test;
import static org.junit.Assert.*;

public class Base64AdapterTest {

	private String primeFileXml =  "<?xml version='1.0' encoding='ISO-8859-1'?>\n" +
			"<XML_FILE>\n" +
			"  <TRANSFER>Y</TRANSFER>\n" +
			"  <MRE_VERSION>7.3</MRE_VERSION>\n" +
			"  <MINOR_VERSION>7.3.385.1</MINOR_VERSION>\n" +
			"  <TABLE_RELEASE_DATE>2019-06-26</TABLE_RELEASE_DATE>\n" +
			"  <PROFILE_NAME>VERSION34</PROFILE_NAME>\n" +
			"  <FILE_NAME>tkEZ02000080_9mjveehlh5h.xml</FILE_NAME>\n" +
			"  <SUBMIT_BY>DE911</SUBMIT_BY>\n" +
			"  <SUBMIT_BY_TRANS>DOWD, JENNIFER</SUBMIT_BY_TRANS>\n" +
			"  <ORG_UNIT>TRAFF</ORG_UNIT>\n" +
			"  <ORG_UNIT_TRANS>TRAFFIC</ORG_UNIT_TRANS>\n" +
			"  <CASE_TYPE>GC</CASE_TYPE>\n" +
			"  <SUBMIT_DATE>2019-06-27</SUBMIT_DATE>\n" +
			"  <SENT_TIME>1214</SENT_TIME>\n" +
			"  <REPORT TYPE=\"TK\">\n" +
			"    <JURISDICTION>DE</JURISDICTION>\n" +
			"    <JURISDICTION_TRANS>DELTA POLICE DEPARTMENT</JURISDICTION_TRANS>\n" +
			"    <TICKET_TYPE>EZ</TICKET_TYPE>\n" +
			"    <TICKET_TYPE_TRANS>EVT TESTING LMD (PRIMECorp Use only)</TICKET_TYPE_TRANS>\n" +
			"    <TICKET_NUM>EZ02000080</TICKET_NUM>\n" +
			"    <TICKET_CLASS>P</TICKET_CLASS>\n" +
			"    <TICKET_CLASS_TRANS>PENALTY</TICKET_CLASS_TRANS>\n" +
			"    <TICKET_STATUS>I</TICKET_STATUS>\n" +
			"    <TICKET_STATUS_TRANS>ISSUED</TICKET_STATUS_TRANS>\n" +
			"    <TICKET_ORIGIN>1</TICKET_ORIGIN>\n" +
			"    <TICKET_ORIGIN_TRANS>MV6010</TICKET_ORIGIN_TRANS>\n" +
			"    <TK_ROLE>DRIVER</TK_ROLE>\n" +
			"    <OFFENCE_DATE>2019-06-27</OFFENCE_DATE>\n" +
			"    <OFFENCE_TIME>1213</OFFENCE_TIME>\n" +
			"    <STREET_NAME>900 BLK YATES ST</STREET_NAME>\n" +
			"    <MUNICIPALITY>VCTA</MUNICIPALITY>\n" +
			"    <MUNICIPALITY_TRANS>VICTORIA</MUNICIPALITY_TRANS>\n" +
			"    <OFFICER_ID>DE911</OFFICER_ID>\n" +
			"    <OFFICER_ID_TRANS>DOWD, JENNIFER</OFFICER_ID_TRANS>\n" +
			"    <PARTNER_ID>DE3718</PARTNER_ID>\n" +
			"    <PARTNER_ID_TRANS>ARMSTRONG, TAYLOR</PARTNER_ID_TRANS>\n" +
			"    <SET_FINE_AMOUNT>109.00</SET_FINE_AMOUNT>\n" +
			"    <AMOUNT_OF_PENALTY>109.00</AMOUNT_OF_PENALTY>\n" +
			"    <PAYMENT_METHOD>A</PAYMENT_METHOD>\n" +
			"    <PAYMENT_METHOD_TRANS>MV6000E (102018)</PAYMENT_METHOD_TRANS>\n" +
			"    <PRINTED>Y</PRINTED>\n" +
			"    <OFFENCE_COUNT>3</OFFENCE_COUNT>\n" +
			"    <CHARGE_TEXT>HOLD BC DRIVER'S LICENCE AT SAME TIME AS ONE PREVIOUSLY ISSUED IN BC OR OTHER JURISDICTION</CHARGE_TEXT>\n" +
			"    <STATUTE_ACT>MV</STATUTE_ACT>\n" +
			"    <LEGAL_STATUTE_SECTION>25(5)</LEGAL_STATUTE_SECTION>\n" +
			"    <PERSON>\n" +
			"      <INDIVIDUAL_SURNAME>JSIT</INDIVIDUAL_SURNAME>\n" +
			"      <GIVEN_ONE>ELIZABETH</GIVEN_ONE>\n" +
			"      <GIVEN_TWO>REGULAR</GIVEN_TWO>\n" +
			"      <GIVEN_THREE>RECORD</GIVEN_THREE>\n" +
			"      <MUNICIPALITY_NAME>VICTORIA</MUNICIPALITY_NAME>\n" +
			"      <PROV_STATE_CODE>BC</PROV_STATE_CODE>\n" +
			"      <PROV_STATE_CODE_TRANS>BRITISH COLUMBIA</PROV_STATE_CODE_TRANS>\n" +
			"      <POSTAL_ZIPCODE>V8W3Y5</POSTAL_ZIPCODE>\n" +
			"      <GENDER_CODE>X</GENDER_CODE>\n" +
			"      <STREET_NAME>910 GOVERNMENT ST</STREET_NAME>\n" +
			"      <DATE_OF_BIRTH>1960-05-05</DATE_OF_BIRTH>\n" +
			"      <DRIVERS_LICENCE_NUMBER>1697172</DRIVERS_LICENCE_NUMBER>\n" +
			"      <DRIVERS_LICENCE_PROV_STATE>BC</DRIVERS_LICENCE_PROV_STATE>\n" +
			"      <DRIVERS_LICENCE_PROV_STATE_TRANS>BRITISH COLUMBIA</DRIVERS_LICENCE_PROV_STATE_TRANS>\n" +
			"    </PERSON>\n" +
			"    <VEHICLE>\n" +
			"      <MODEL_YEAR>2020</MODEL_YEAR>\n" +
			"      <VEHICLE_MAKE>FORD</VEHICLE_MAKE>\n" +
			"      <VEHICLE_MAKE_TRANS>FORD</VEHICLE_MAKE_TRANS>\n" +
			"      <STYLE>4DR</STYLE>\n" +
			"      <STYLE_TRANS>4-DOOR SEDAN</STYLE_TRANS>\n" +
			"      <ORIGINAL_COLOUR>SIL</ORIGINAL_COLOUR>\n" +
			"      <ORIGINAL_COLOUR_TRANS>SILVER/ALUMINUM/STAINLESS STEEL</ORIGINAL_COLOUR_TRANS>\n" +
			"    </VEHICLE>\n" +
			"    <CUSTOMDATA>\n" +
			"      <TK_DL_EXPIRY>2021</TK_DL_EXPIRY>\n" +
			"      <TK_REG_OWNER_NAME>HARRY LUNGPAYNE</TK_REG_OWNER_NAME>\n" +
			"      <TK_DISPUTE_LOCATION_ADDRESS_TRANS>955 Wharf St, Victoria, B.C.</TK_DISPUTE_LOCATION_ADDRESS_TRANS>\n" +
			"      <TK_COURT_HEARING_LOCATION_TRANS>VICTORIA, B.C.</TK_COURT_HEARING_LOCATION_TRANS>\n" +
			"      <TK_WITNESSING_OFFICER>DE929</TK_WITNESSING_OFFICER>\n" +
			"      <TK_WITNESSING_OFFICER_TRANS>ANNESLEY, SCOTT</TK_WITNESSING_OFFICER_TRANS>\n" +
			"      <TK_CERTIFICATE_ENTITY_PERSON>Y</TK_CERTIFICATE_ENTITY_PERSON>\n" +
			"      <TK_TEMP_OFFICER_LASTNAME>DOWD</TK_TEMP_OFFICER_LASTNAME>\n" +
			"      <TK_TEMP_WITNESSING_OFFICER_LASTNAME>ANNESLEY</TK_TEMP_WITNESSING_OFFICER_LASTNAME>\n" +
			"      <TK_CERTIFICATE>Y</TK_CERTIFICATE>\n" +
			"      <TK_CERTIFICATE_SERVED_TO>ELIZABETH REGULAR RECORD JSIT</TK_CERTIFICATE_SERVED_TO>\n" +
			"      <TK_CERTIFICATE_DATE_OF_SERVICE>2019-06-27</TK_CERTIFICATE_DATE_OF_SERVICE>\n" +
			"    </CUSTOMDATA>\n" +
			"  </REPORT>\n" +
			"</XML_FILE>";;

			private String base64String = "PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nSVNPLTg4NTktMSc/Pgo8WE1MX0ZJTEU+CiAgPFRSQU5TRkVSPlk8L1RSQU5TRkVSPgogIDxNUkVfVkVSU0lPTj43LjM8L01SRV9WRVJTSU9OPgogIDxNSU5PUl9WRVJTSU9OPjcuMy4zODUuMTwvTUlOT1JfVkVSU0lPTj4KICA8VEFCTEVfUkVMRUFTRV9EQVRFPjIwMTktMDYtMjY8L1RBQkxFX1JFTEVBU0VfREFURT4KICA8UFJPRklMRV9OQU1FPlZFUlNJT04zNDwvUFJPRklMRV9OQU1FPgogIDxGSUxFX05BTUU+dGtFWjAyMDAwMDgwXzltanZlZWhsaDVoLnhtbDwvRklMRV9OQU1FPgogIDxTVUJNSVRfQlk+REU5MTE8L1NVQk1JVF9CWT4KICA8U1VCTUlUX0JZX1RSQU5TPkRPV0QsIEpFTk5JRkVSPC9TVUJNSVRfQllfVFJBTlM+CiAgPE9SR19VTklUPlRSQUZGPC9PUkdfVU5JVD4KICA8T1JHX1VOSVRfVFJBTlM+VFJBRkZJQzwvT1JHX1VOSVRfVFJBTlM+CiAgPENBU0VfVFlQRT5HQzwvQ0FTRV9UWVBFPgogIDxTVUJNSVRfREFURT4yMDE5LTA2LTI3PC9TVUJNSVRfREFURT4KICA8U0VOVF9USU1FPjEyMTQ8L1NFTlRfVElNRT4KICA8UkVQT1JUIFRZUEU9IlRLIj4KICAgIDxKVVJJU0RJQ1RJT04+REU8L0pVUklTRElDVElPTj4KICAgIDxKVVJJU0RJQ1RJT05fVFJBTlM+REVMVEEgUE9MSUNFIERFUEFSVE1FTlQ8L0pVUklTRElDVElPTl9UUkFOUz4KICAgIDxUSUNLRVRfVFlQRT5FWjwvVElDS0VUX1RZUEU+CiAgICA8VElDS0VUX1RZUEVfVFJBTlM+RVZUIFRFU1RJTkcgTE1EIChQUklNRUNvcnAgVXNlIG9ubHkpPC9USUNLRVRfVFlQRV9UUkFOUz4KICAgIDxUSUNLRVRfTlVNPkVaMDIwMDAwODA8L1RJQ0tFVF9OVU0+CiAgICA8VElDS0VUX0NMQVNTPlA8L1RJQ0tFVF9DTEFTUz4KICAgIDxUSUNLRVRfQ0xBU1NfVFJBTlM+UEVOQUxUWTwvVElDS0VUX0NMQVNTX1RSQU5TPgogICAgPFRJQ0tFVF9TVEFUVVM+STwvVElDS0VUX1NUQVRVUz4KICAgIDxUSUNLRVRfU1RBVFVTX1RSQU5TPklTU1VFRDwvVElDS0VUX1NUQVRVU19UUkFOUz4KICAgIDxUSUNLRVRfT1JJR0lOPjE8L1RJQ0tFVF9PUklHSU4+CiAgICA8VElDS0VUX09SSUdJTl9UUkFOUz5NVjYwMTA8L1RJQ0tFVF9PUklHSU5fVFJBTlM+CiAgICA8VEtfUk9MRT5EUklWRVI8L1RLX1JPTEU+CiAgICA8T0ZGRU5DRV9EQVRFPjIwMTktMDYtMjc8L09GRkVOQ0VfREFURT4KICAgIDxPRkZFTkNFX1RJTUU+MTIxMzwvT0ZGRU5DRV9USU1FPgogICAgPFNUUkVFVF9OQU1FPjkwMCBCTEsgWUFURVMgU1Q8L1NUUkVFVF9OQU1FPgogICAgPE1VTklDSVBBTElUWT5WQ1RBPC9NVU5JQ0lQQUxJVFk+CiAgICA8TVVOSUNJUEFMSVRZX1RSQU5TPlZJQ1RPUklBPC9NVU5JQ0lQQUxJVFlfVFJBTlM+CiAgICA8T0ZGSUNFUl9JRD5ERTkxMTwvT0ZGSUNFUl9JRD4KICAgIDxPRkZJQ0VSX0lEX1RSQU5TPkRPV0QsIEpFTk5JRkVSPC9PRkZJQ0VSX0lEX1RSQU5TPgogICAgPFBBUlRORVJfSUQ+REUzNzE4PC9QQVJUTkVSX0lEPgogICAgPFBBUlRORVJfSURfVFJBTlM+QVJNU1RST05HLCBUQVlMT1I8L1BBUlRORVJfSURfVFJBTlM+CiAgICA8U0VUX0ZJTkVfQU1PVU5UPjEwOS4wMDwvU0VUX0ZJTkVfQU1PVU5UPgogICAgPEFNT1VOVF9PRl9QRU5BTFRZPjEwOS4wMDwvQU1PVU5UX09GX1BFTkFMVFk+CiAgICA8UEFZTUVOVF9NRVRIT0Q+QTwvUEFZTUVOVF9NRVRIT0Q+CiAgICA8UEFZTUVOVF9NRVRIT0RfVFJBTlM+TVY2MDAwRSAoMTAyMDE4KTwvUEFZTUVOVF9NRVRIT0RfVFJBTlM+CiAgICA8UFJJTlRFRD5ZPC9QUklOVEVEPgogICAgPE9GRkVOQ0VfQ09VTlQ+MzwvT0ZGRU5DRV9DT1VOVD4KICAgIDxDSEFSR0VfVEVYVD5IT0xEIEJDIERSSVZFUidTIExJQ0VOQ0UgQVQgU0FNRSBUSU1FIEFTIE9ORSBQUkVWSU9VU0xZIElTU1VFRCBJTiBCQyBPUiBPVEhFUiBKVVJJU0RJQ1RJT048L0NIQVJHRV9URVhUPgogICAgPFNUQVRVVEVfQUNUPk1WPC9TVEFUVVRFX0FDVD4KICAgIDxMRUdBTF9TVEFUVVRFX1NFQ1RJT04+MjUoNSk8L0xFR0FMX1NUQVRVVEVfU0VDVElPTj4KICAgIDxQRVJTT04+CiAgICAgIDxJTkRJVklEVUFMX1NVUk5BTUU+SlNJVDwvSU5ESVZJRFVBTF9TVVJOQU1FPgogICAgICA8R0lWRU5fT05FPkVMSVpBQkVUSDwvR0lWRU5fT05FPgogICAgICA8R0lWRU5fVFdPPlJFR1VMQVI8L0dJVkVOX1RXTz4KICAgICAgPEdJVkVOX1RIUkVFPlJFQ09SRDwvR0lWRU5fVEhSRUU+CiAgICAgIDxNVU5JQ0lQQUxJVFlfTkFNRT5WSUNUT1JJQTwvTVVOSUNJUEFMSVRZX05BTUU+CiAgICAgIDxQUk9WX1NUQVRFX0NPREU+QkM8L1BST1ZfU1RBVEVfQ09ERT4KICAgICAgPFBST1ZfU1RBVEVfQ09ERV9UUkFOUz5CUklUSVNIIENPTFVNQklBPC9QUk9WX1NUQVRFX0NPREVfVFJBTlM+CiAgICAgIDxQT1NUQUxfWklQQ09ERT5WOFczWTU8L1BPU1RBTF9aSVBDT0RFPgogICAgICA8R0VOREVSX0NPREU+WDwvR0VOREVSX0NPREU+CiAgICAgIDxTVFJFRVRfTkFNRT45MTAgR09WRVJOTUVOVCBTVDwvU1RSRUVUX05BTUU+CiAgICAgIDxEQVRFX09GX0JJUlRIPjE5NjAtMDUtMDU8L0RBVEVfT0ZfQklSVEg+CiAgICAgIDxEUklWRVJTX0xJQ0VOQ0VfTlVNQkVSPjE2OTcxNzI8L0RSSVZFUlNfTElDRU5DRV9OVU1CRVI+CiAgICAgIDxEUklWRVJTX0xJQ0VOQ0VfUFJPVl9TVEFURT5CQzwvRFJJVkVSU19MSUNFTkNFX1BST1ZfU1RBVEU+CiAgICAgIDxEUklWRVJTX0xJQ0VOQ0VfUFJPVl9TVEFURV9UUkFOUz5CUklUSVNIIENPTFVNQklBPC9EUklWRVJTX0xJQ0VOQ0VfUFJPVl9TVEFURV9UUkFOUz4KICAgIDwvUEVSU09OPgogICAgPFZFSElDTEU+CiAgICAgIDxNT0RFTF9ZRUFSPjIwMjA8L01PREVMX1lFQVI+CiAgICAgIDxWRUhJQ0xFX01BS0U+Rk9SRDwvVkVISUNMRV9NQUtFPgogICAgICA8VkVISUNMRV9NQUtFX1RSQU5TPkZPUkQ8L1ZFSElDTEVfTUFLRV9UUkFOUz4KICAgICAgPFNUWUxFPjREUjwvU1RZTEU+CiAgICAgIDxTVFlMRV9UUkFOUz40LURPT1IgU0VEQU48L1NUWUxFX1RSQU5TPgogICAgICA8T1JJR0lOQUxfQ09MT1VSPlNJTDwvT1JJR0lOQUxfQ09MT1VSPgogICAgICA8T1JJR0lOQUxfQ09MT1VSX1RSQU5TPlNJTFZFUi9BTFVNSU5VTS9TVEFJTkxFU1MgU1RFRUw8L09SSUdJTkFMX0NPTE9VUl9UUkFOUz4KICAgIDwvVkVISUNMRT4KICAgIDxDVVNUT01EQVRBPgogICAgICA8VEtfRExfRVhQSVJZPjIwMjE8L1RLX0RMX0VYUElSWT4KICAgICAgPFRLX1JFR19PV05FUl9OQU1FPkhBUlJZIExVTkdQQVlORTwvVEtfUkVHX09XTkVSX05BTUU+CiAgICAgIDxUS19ESVNQVVRFX0xPQ0FUSU9OX0FERFJFU1NfVFJBTlM+OTU1IFdoYXJmIFN0LCBWaWN0b3JpYSwgQi5DLjwvVEtfRElTUFVURV9MT0NBVElPTl9BRERSRVNTX1RSQU5TPgogICAgICA8VEtfQ09VUlRfSEVBUklOR19MT0NBVElPTl9UUkFOUz5WSUNUT1JJQSwgQi5DLjwvVEtfQ09VUlRfSEVBUklOR19MT0NBVElPTl9UUkFOUz4KICAgICAgPFRLX1dJVE5FU1NJTkdfT0ZGSUNFUj5ERTkyOTwvVEtfV0lUTkVTU0lOR19PRkZJQ0VSPgogICAgICA8VEtfV0lUTkVTU0lOR19PRkZJQ0VSX1RSQU5TPkFOTkVTTEVZLCBTQ09UVDwvVEtfV0lUTkVTU0lOR19PRkZJQ0VSX1RSQU5TPgogICAgICA8VEtfQ0VSVElGSUNBVEVfRU5USVRZX1BFUlNPTj5ZPC9US19DRVJUSUZJQ0FURV9FTlRJVFlfUEVSU09OPgogICAgICA8VEtfVEVNUF9PRkZJQ0VSX0xBU1ROQU1FPkRPV0Q8L1RLX1RFTVBfT0ZGSUNFUl9MQVNUTkFNRT4KICAgICAgPFRLX1RFTVBfV0lUTkVTU0lOR19PRkZJQ0VSX0xBU1ROQU1FPkFOTkVTTEVZPC9US19URU1QX1dJVE5FU1NJTkdfT0ZGSUNFUl9MQVNUTkFNRT4KICAgICAgPFRLX0NFUlRJRklDQVRFPlk8L1RLX0NFUlRJRklDQVRFPgogICAgICA8VEtfQ0VSVElGSUNBVEVfU0VSVkVEX1RPPkVMSVpBQkVUSCBSRUdVTEFSIFJFQ09SRCBKU0lUPC9US19DRVJUSUZJQ0FURV9TRVJWRURfVE8+CiAgICAgIDxUS19DRVJUSUZJQ0FURV9EQVRFX09GX1NFUlZJQ0U+MjAxOS0wNi0yNzwvVEtfQ0VSVElGSUNBVEVfREFURV9PRl9TRVJWSUNFPgogICAgPC9DVVNUT01EQVRBPgogIDwvUkVQT1JUPgo8L1hNTF9GSUxFPg==";

	@Test
	public void marshalTest() throws Exception {
				assertEquals(base64String, new Base64Adapter().marshal(primeFileXml));

	}

	@Test
	public void unmarshalTest() throws Exception {
		assertEquals(primeFileXml, new Base64Adapter().unmarshal(base64String));
	}
}