global:
  scrape_interval: 5s


scrape_configs:
  - job_name: 'api-geocoder-service'
    metrics_path: /geocodersvc/actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: geocodersvc