<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="RSI_InformationManager" targetNamespace="http://icbc.net/RSI_InformationManager" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://icbc.net/RSI_InformationManager" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:documentation>
		<Service>RSI_InformationManager</Service>
		<Version>2.0</Version>
		<Created>2017-02-20</Created>
		<Author>M. Darke</Author>
	
  
  
  
  
  <appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="RSI_InformationManager_Binding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </appinfo>
  </wsdl:documentation>
	<wsdl:types>
		<xsd:schema targetNamespace="http://icbc.net/RSI_InformationManager">
<xsd:include schemaLocation="RSI_InformationManager.xsd">
			</xsd:include>
</xsd:schema>
	</wsdl:types>
	<wsdl:message name="CreateContraventionRequest">
		<wsdl:part element="tns:createContraventionRequest" name="createContraventionRequest"/>
	</wsdl:message>
	<wsdl:message name="CreateContraventionResponse">
		<wsdl:part element="tns:createContraventionResponse" name="createContraventionResponse"/>
	</wsdl:message>
	<wsdl:portType name="RSI_InformationManager_PortType">
		<wsdl:operation name="CreateContravention">
			<wsdl:input message="tns:CreateContraventionRequest"/>
			<wsdl:output message="tns:CreateContraventionResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="RSI_InformationManager_Binding" type="tns:RSI_InformationManager_PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="CreateContravention">
			<soap:operation soapAction="CreateContravention"/>
			<wsdl:input>
				<soap:body parts="createContraventionRequest" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="createContraventionResponse" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="RSI_InformationManager_Service">
		<wsdl:port binding="tns:RSI_InformationManager_Binding" name="RSI_InformationManager_Port">
			<soap:address location="https://b2bmrg.icbc.com:440/RSI_InformationManager"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>