name: cd-workflow

on:
  workflow_call:
    inputs:
      DOCKER_CONTEXT:
        required: true
        type: string
      DOCKER_FILE:
        required: true
        type: string
      DOCKER_IMAGE_NAME:
        required: true
        type: string
      DOCKER_IMAGE_TAG:
        required: false
        type: string
        default: latest
    secrets:
      DOCKER_REGISTRY:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  trivy-scan:
    uses: ./.github/workflows/trivy-scan-workflow.yml
    with:
      DOCKER_CONTEXT: ${{ inputs.DOCKER_CONTEXT }}
      DOCKER_FILE: ${{ inputs.DOCKER_FILE }}
      DOCKER_IMAGE_NAME: ${{ inputs.DOCKER_IMAGE_NAME }}
    secrets: inherit
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    if: startsWith(github.event.pull_request.head.ref, 'release')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.DOCKER_CONTEXT }}
          file: ${{ inputs.DOCKER_FILE }}
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{ inputs.DOCKER_IMAGE_NAME }}:${{ inputs.DOCKER_IMAGE_TAG }}


          

