name: Geocoder-Build & Deploy to DEV
on:
  pull_request:
    types: [opened, reopened,edited,synchronize]
    branches:   
      - 'devbranch'
    paths:
      - rsbc-ride-geocoder-svc/**


jobs:
   trivy-scan:
    uses: ./.github/workflows/trivy-scan-workflow.yml
    with:
      DOCKER_CONTEXT: rsbc-ride-geocoder-svc
      DOCKER_FILE: rsbc-ride-geocoder-svc/Dockerfile
      DOCKER_IMAGE_NAME: rsbc-ride-geocoder-svc
    secrets: inherit
   run_unit_test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: trivy-scan
    environment: pr
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3   
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run unit tests
        run: |
          cd rsbc-ride-geocoder-svc
          mvn clean compile test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: './rsbc-ride-geocoder-svc/target/surefire-reports/TEST-*.xml'

   build:
    name: Build and Push
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.head.ref, 'release-geocoder/')
    environment: dev
    needs: [trivy-scan,run_unit_test]
    env:
      DOCKER_IMAGE_TAG: ${{ github.sha}}
      DOCKER_CONTEXT_FOLDER: rsbc-ride-geocoder-svc
      DOCKER_IMAGE_NAME: rbe5-images/ride-geocoder-svc
      DOCKER_FILE: rsbc-ride-geocoder-svc/Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.DOCKER_CONTEXT_FOLDER }}
          file: ${{ env.DOCKER_FILE }}
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
   deploy_dev_argocd:
    name: Push to Gitops repo for Dev deployment via Argocd
    runs-on: ubuntu-latest
    needs: [trivy-scan,run_unit_test,build]
    env:
      PR_NUMBER: ${{ github.event.number }}
      PR_IMAGE_STREAM_TAG: ${{ github.sha}}
      RELEASE_NAME: release_1_0
    steps:
      - name: Checkout Gitops repository
        uses: actions/checkout@v3
        with:
          repository: bcgov-c/tenant-gitops-be5301
          ref: deployment/rsbc-ride-api-svcs
          token: ${{ secrets.GITOPS_GITHUB_TOKEN }}
      - name: Update Image tag for Dev deploy
        uses: mikefarah/yq@v4.28.1
        with:
          cmd: yq eval -i '.images[0].newTag = "${{env.PR_IMAGE_STREAM_TAG}}"' 'geocoder-api/overlays/dev/kustomization.yaml'
      - name: Update release name for Dev deploy
        uses: mikefarah/yq@v4.28.1
        with:
          cmd: yq eval -i '.commonAnnotations.release_name = "${{env.RELEASE_NAME}}"' 'geocoder-api/overlays/dev/kustomization.yaml'
      - name: Update sha annotation
        uses: mikefarah/yq@v4.28.1
        with:
          cmd: yq eval -i '.commonAnnotations.commit_sha = "${{env.PR_IMAGE_STREAM_TAG}}"' 'geocoder-api/overlays/dev/kustomization.yaml'
      - name: Check Changed value
        run: |
          cat geocoder-api/overlays/dev/kustomization.yaml
      - name: Push Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "updated dev deploy details to dev overlay yaml"
          git push -u origin deployment/rsbc-ride-api-svcs

  
        